### ISSUE TITLE
wrong ipv6 on AAAA record

### ISSUE THREAD

**Issue by alexandre1985** [oborseth/porkbun-dynamic-dns-java#1]
I am using this program since I am clueless how to use `curl` to edit DNS records, using the API.

So, this program works fine for A records 👍
When trying DDNS an ipv6 AAAA record, it puts in the record the ipv4 address. I would like for this program update the ipv6 AAAA record with my ipv6 (not ipv4) ip.

Can this be done?

**Comment by alexandre1985** [comment]
I have made this work with this pull request https://github.com/oborseth/porkbun-dynamic-dns-java/pull/2

**Comment by oborseth** [comment]
Thank you! I've merged the pull request.
