### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by alexandre1985** [oborseth/porkbun-dynamic-dns-java#4]
I would like an FLOSS license on this project.
Or else, create a LICENSE file in order for contributors to know what to expect 😉

**Comment by alexandre1985** [comment]
In short, without a license, the only thing I can safely assume is that I have no rights to do anything at all with this code.
Because the code defaults to _all rights reserved_ .
In the particular case of GitHub, I can only fork the repository and view the code, but nothing more.

I would like to modify (more), run, distribute this code, so can you please grant me an explicit authorization to do so?
Or maybe put an permissive license to do so?

**Comment by oborseth** [comment]
Sorry for the delay. I've put an MIT license on it.

**Comment by alexandre1985** [comment]
Nice!
